### PR TITLE
fix(#59): correctly parse negative numbers in cleanInteger()

### LINKED ISSUE #59: incorrect values displayed in AES Flight Information
Reported by [oxmoxtatze on discord](https://discord.com/channels/113555701774749696/1249639537450160138/1250051323982778450)

Reported AES output:
table with positive numbers

Actual flight data:
table with negative numbers

### PR DESCRIPTION
**Pull request by ZoeBijl**
Closes #59 

The regex was stripping away vital information; this new version preserves this information when necessary.

### CODE REVIEW

File: extension/helpers.js [hunk 1]
```diff
@@ -159,12 +159,19 @@ class AES {
     
     /**
      * Cleans a string of punctuation to returns an integer
-     * @param {string} "2,000 AS$" | "2.000 AS$"
+     * @param {string} value - "2,000 AS$" | "2.000 AS$"
      * @returns {integer} 2000
      */
     static cleanInteger(value) {
+        value = value.trim()
+        const isCurrency = value.match(/\$$/g)?.length
```
Comment (alice) [inline extension/helpers.js]:
```suggestion
        const isCurrency = value.match(/\$$/g)
```

Since `.match()` returns `null` if the regex doesn't match, you can just use the return value directly. If you'd like to explicitly cast it to a boolean, you can use `Boolean(...)` or `!!(...)`.

File: extension/helpers.js [hunk 2]
```diff
@@ -159,12 +159,19 @@ class AES {
...
+        const isNegative = value.match(/^[-]/g)?.length
```
Comment (alice) [inline extension/helpers.js]:
```suggestion
```

`parseInt()` knows how to parse negative numbers, so we can improve our regex below instead.

File: extension/helpers.js [hunk 3]
```diff
@@ -159,12 +159,19 @@ class AES {
...
+
         // \D matches any character that's not a digit
         let result = value.replaceAll(/\D+/g, "")
```
Comment (alice) [inline extension/helpers.js]:
```suggestion
        let result = value.replaceAll(/[^\d-]/g, "")
```

Replace everything that's _not_ a digit or a negative sign with `""`

File: extension/helpers.js [hunk 4]
```diff
@@ -159,12 +159,19 @@ class AES {
...
+        if (isNegative) {
+            result = result * -1
+        }
```
Comment (alice) [inline extension/helpers.js]:
```suggestion
```

If we leave the `-` intact, `parseInt()` can parse negative numbers.

File: extension/helpers.js [hunk 5]
```diff
@@ -159,12 +159,19 @@ class AES {
...
-     * @param {string} "2,000 AS$" | "2.000 AS$"
+     * @param {string} value - "2,000 AS$" | "2.000 AS$"
      * @returns {integer} 2000
      */
     static cleanInteger(value) {
+        value = value.trim()
+        const isCurrency = value.match(/\$$/g)?.length
+        const isNegative = value.match(/^[-]/g)?.length
+
         // \D matches any character that's not a digit
```
Comment (alice) [inline extension/helpers.js]: If you use the below suggestion, this comment will also need to be updated :)

**Review by alice — APPROVED** [review]
Some suggestions below!

File: extension/helpers.js (hunk 1 above)
Comment (ZoeBijl) [reply extension/helpers.js]: I didn’t know about `Boolean()`; that looks useful!
